[package]
name = "autonatv2"
version = "0.1.0"
edition.workspace = true
publish = false
license = "MIT or Apache-2.0"

[package.metadata.release]
release = false

[[bin]]
name = "autonatv2_client"

[[bin]]
name = "autonatv2_server"

[dependencies]
libp2p = { workspace = true, features = ["macros", "tokio", "tcp", "noise", "yamux", "autonat", "identify", "dns", "quic"] }
clap = { version = "4.4.18", features = ["derive"] }
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
rand = "0.8.5"
opentelemetry = { version = "0.27.0", optional = true }
opentelemetry_sdk = { version = "0.27.0", optional = true, features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.27.0", optional = true }
tracing-opentelemetry = { version = "0.28.0", optional = true }
cfg-if = "1.0.0"

[features]
jaeger = ["opentelemetry", "opentelemetry_sdk", "opentelemetry-otlp", "tracing-opentelemetry"]
opentelemetry = ["dep:opentelemetry"]
opentelemetry_sdk = ["dep:opentelemetry_sdk"]
opentelemetry-otlp = ["dep:opentelemetry-otlp"]
tracing-opentelemetry = ["dep:tracing-opentelemetry"]

[lints]
workspace = true
