services:
    autonatv2:
        build:
            context: ../..
            dockerfile: examples/autonatv2/Dockerfile
        environment:
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
        ports:
            - "4884:4884"
        depends_on:
            - jaeger
    jaeger:
        image: jaegertracing/all-in-one
        environment:
            - COLLECTOR_OTLP_ENABLED=true
        ports:
            - "4317:4317"
            - "16686:16686"
